load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")

cc_binary(
    name = "sort",                                                           
    srcs = [
        "sort.cc",
        "quicksort.cc",
        "mergesort.cc",
        "insertsort.cc",
        "findkth.cc"
    ],
    hdrs = ["sort.h", "../common.h"],
)
