load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")

cc_binary(                                                                          
    name = "sort",                                                           
    srcs = [
        "sort.cpp",
        "quicksort.cpp",
        "mergesort.cpp",
        "insertsort.cpp",
        "findkth.cpp"
    ],
    hdrs = ["sort.h", "../common.h"],
)